defaults: &defaults
  #basic_auth: false
  #basic_auth_user: 
  #basic_auth_password: 
  #site_name: 

  FACEBOOK_KEY:
  FACEBOOK_SECRET:

  SENDGRID_USERNAME:
  SENDGRID_PASSWORD:
  SENDGRID_DOMAIN: 

  AMAZON_KEY: # CREDs for amazon product advertising api
  AMAZON_SECRET:
  AMAZON_TAG:

Development:
  <<: *defaults

test:
  <<: *defaults

staging:
  <<: *defaults

production:
  <<: *defaults
